name: GitHub Pages

on:
  push:
    branches:
    - dev

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - uses: leafo/gh-actions-lua@v8.0.0

    # I'm so sorry for the following perl command.
    - name: Generate index.md
      run: |
        bin/mk-loader.lua loader.lua
        perl -i -pe "s/%LOADER%/$(sed -e 's/[\/&]/\\&/g' loader.lua)/g" doc/notes/usage.md

    - name: Generate repositories
      run: |
        bin/mk-repo.lua packman ./_site/packlist
        bin/mk-repo.lua ccpt ./_site/ccpt.json

    - name: Generate documentation
      run: |
        test -d bin || mkdir bin
        test -f bin/illuaminate || wget -q -Obin/illuaminate https://squiddev.cc/illuaminate/linux-x86-64/illuaminate
        chmod +x bin/illuaminate
        bin/illuaminate doc-gen

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_site
        force_orphan: true
        commit_message: Build for
